### ISSUE TITLE
Question about Storage

### ISSUE THREAD

**Issue by sonoroot** [citynetwork/citycloud-examples#1]
Hi Stefano,
nice work!
I'm not a CityCloud user, my question is more towards a vanilla/standard Openstack installation.

Would this deployment support out of the box Cinder? If I create a PVC right after deployment (without tinkering with Rancher node drivers), would it work? 

I had hard time having Rancher properly setup a storage class on Cinder (mainly due to the docker-machine compatibility with OS API).

I do also Terraform the entire stack, however Rancher supports fell a bit short around Openstack (and were I work we deploy tens of Rancher clusters a months on different clouds).

Any thought/advice?
Thanks for sharing!

**Comment by xstecuc** [comment]
Hi!

The most important thing when setting up a storage class is to edit the Openstack configuration as a volume provider.

So edit your cluster Rancher yaml file or Terraform configuration adding:

```
cloud_provider:
  name: "openstack"
  openstackCloudProvider:
    block_storage: 
      ignore-volume-az: true
      trust-device-path: false
    global:
      auth-url: "https://fra1.citycloud.com:5000/v3/" 
      domain-id: "<your_domain_id>" 
      tenant-id: "<your_tenant_id>" 
      username: "<your_username>" 
      password: "<your_password>" 
    metadata:
      request-timeout: 0
```

Then create a Storage Class with Openstack Cinder Volume as 'Provider' and a Persistent Volume assigned to this SC. You can finally create a PVC from a persistent volume or storage class. 

An example.

When setting Harbor up as container registry you can use Answers to attach the volumes: 
```
persistence.persistentVolumeClaim.registry.storageClass = harbor
persistence.persistentVolumeClaim.chartmuseum.storageClass = harbor
persistence.persistentVolumeClaim.jobservice.storageClass = harbor
persistence.persistentVolumeClaim.database.storageClass = harbor
persistence.persistentVolumeClaim.redis.storageClass = harbor

```

I hope this answered your question and you found it useful.

About Rancher support around Openstack, I think they are doing a good job overall but yes, you might sometimes need workarounds to overcome issues but communities together are coping very well by being very active and mature.
